const MAPPING_TEXT = {
  DRAG_MODE:"拖拽模式",
  DRAG_MODE_DESC:"拖拽模式下，点击节点可以进行移动，点击连线可以进行编辑。",
  LASSO_MODE:"框选模式",
  LASSO_MODE_DESC:"框选模式下，点击节点可以进行移动，点击连线可以进行编辑。",
  FIT_VIEW:"适应视图",
  ZOOM_SELECT:"缩放选择",
  SAVE:"保存",
  MINIMAP:"小地图",
  AUTO_LAYOUT:"自动布局",
  SWITCH_LINE:"切换连线",
  INTERACTION_MODE:"交互模式",
  ADD_NODE:"添加节点",
  ADD:"添加",
  SWITCH_EDGE:"转换连线",
  DELETE:"删除",
  UNDO:"撤销",
  REDO:"重做",
  TITLE_IS_REQUIRED:"标题不能为空",
  CONDITION_IS_REQUIRED:"条件不能为空",
  PROMPT_IS_REQUIRED:"提示不能为空",
  IS_REQUIRED:"不能为空",
  START_TITLE:"开始",
  START_DESC:"工作流的起始节点，用于设置启动工作流所需的信息。",
  END_TITLE:"结束",
  END_DESC:"工作流的最终节点，用于在工作流运行后返回结果信息。",
  CONDITION:"condition",
  CONDITION_TITLE:"条件",
  CONDITION_DESC:"连接多个下游分支。只有在满足设定条件时，才会执行对应的分支。",
  LLM_DESC:"调用大语言模型，使用变量和提示词生成响应。",
  LLM_TITLE:"大型语言模型",
  MODEL_TYPE:"模型类型",
  TEMPERATURE:"创意度",
  SYSTEM_PROMPT:"系统设定",
  SYSTEM_PROMPT_CONTENT:"AI大模型助手",
  PROMPT:"任务描述",
  LOOP_TITLE:"循环",
  LOOP_DESC:"重复执行一组任务，根据设定的次数或逻辑进行。",
  LOOP_TIMES: "循环次数",
  NODES_COPIED: "节点已复制",
  NODES_FAILED_COPIED: "节点复制失败",
  NODES_FAILED_PASTED: "节点粘贴失败",
  NODES_PASTED_FAILED_FROM_DIFFERENT_PAGES:"节点粘贴失败，请从相同页面粘贴",
  NODES_PASTED: "节点已粘贴",
  CREATE_COPY:"创建副本",
  SELECT_VARIABLE:"选择变量"
}
const NODE_TYPE={
  START:"start",
  CONDITION:"condition",
  LLM:"llm",
  END:"end",
  LOOP:"loop",
}
export {MAPPING_TEXT,NODE_TYPE}
